name: Build and Commit Changes

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build rules list
        runs-on: ubuntu-latest
        if: ${{!contains(github.event.head_commit.message, '[skip ci]')}}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'

            - name: Build project
              run: npm run build

            - name: Check for changes in dist folder
              id: check_changes
              run: |
                  git diff --quiet HEAD -- dist || echo "::set-output name=changes::true"

            - name: Commit changes
              if: steps.check_changes.outputs.changes == 'true'
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                    commit_message: "ci: update dist [skip ci]"
                    commit_options: "--no-verify"
                    file_pattern: dist/*
                    commit_user_name: "GitHub Actions"
                    commit_user_email: "github-actions[bot]@users.noreply.github.com"
                    github_token: ${{ secrets.GITHUB_TOKEN }}
